###user signup endpoint
POST http://localhost:4030/v1/user
Content-Type: application/json

{
    "name":"hussien alikhani",
    "phone":"09354535833",
    "email":"e1@e.com",
    "password":"secret123",
    "company":"farazin",
    "address":"some address in tehran"
}

###user signin endpoint
POST http://localhost:4030/v1/user/login
Content-Type: application/json

{

    "email":"e1@e.com",
    "password":"secret123"

}

###user signin endpoint
GET  http://localhost:4030/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImUxQGUuY29tIiwiaWF0IjoxNjMwMzE4Nzc1LCJleHAiOjE2MzA0MDUxNzV9.huHAGhqgvac1_qTDgWpHND5fgIBWfaH-j5aluH-x0rQ

### Get refreshed token
GET http://localhost:4030/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImUxQGUuY29tIiwiaWF0IjoxNjMwMzE4Nzc1LCJleHAiOjE2MzI5MTA3NzV9.UDzHjG8tXrLGXODlQOdP7U24FaMJDQ3k7ridI2dEx5k
